import Movie from '../models/Movie.js';
import Show from '../models/Show.js';
import asyncHandler from '../utils/asyncHandler.js';

/**
 * @desc    Get all movies (Admin)
 * @route   GET /api/admin/movies
 * @access  Private/Admin
 */
export const getAllMovies = asyncHandler(async (req, res) => {
  const movies = await Movie.find({}).sort({ createdAt: -1 });
  res.json({
    success: true,
    count: movies.length,
    data: movies
  });
});

/**
 * @desc    Add a new movie
 * @route   POST /api/admin/movies
 * @access  Private/Admin
 */
export const addMovie = asyncHandler(async (req, res) => {
  const movie = await Movie.create(req.body);
  res.status(201).json({
    success: true,
    data: movie
  });
});

/**
 * @desc    Get all shows (Admin)
 * @route   GET /api/admin/shows
 * @access  Private/Admin
 */
export const getAllShows = asyncHandler(async (req, res) => {
  const shows = await Show.find({})
    .populate('movieId', 'title language duration')
    .sort({ time: 1 });
    
  res.json({
    success: true,
    count: shows.length,
    data: shows
  });
});

/**
 * @desc    Add a new show
 * @route   POST /api/admin/shows
 * @access  Private/Admin
 */
export const addShow = asyncHandler(async (req, res) => {
  const { movieId, time } = req.body;

  // Check if movie exists
  const movie = await Movie.findById(movieId);
  if (!movie) {
    res.status(404);
    throw new Error('Movie not found');
  }

  // seats are auto-generated by Show model pre-save hook
  // even if seats are passed in req.body, Show.create only uses movieId and time here
  const show = await Show.create({ movieId, time });
  
  res.status(201).json({
    success: true,
    data: show
  });
});

/**
 * @desc    Delete a movie
 * @route   DELETE /api/admin/movies/:id
 * @access  Private/Admin
 */
export const deleteMovie = asyncHandler(async (req, res) => {
  const movie = await Movie.findById(req.params.id);
  if (!movie) {
    res.status(404);
    throw new Error('Movie not found');
  }

  // Delete associated shows as well
  await Show.deleteMany({ movieId: req.params.id });
  await movie.deleteOne();

  res.json({
    success: true,
    message: 'Movie and associated shows removed'
  });
});
